/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionarygui;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.sun.glass.events.KeyEvent;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.awt.Color;
import java.awt.List;
import java.awt.TextField;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javazoom.jl.player.Player;


/**
 *
 * @author Administrator
 */
public class DictionaryForm extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryForm
     */
    
    static DefaultListModel defautListModel = new DefaultListModel();
    private TextAutoCompleter textac;
    Dictionary dc = new Dictionary();
    
    public DictionaryForm() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("if_accessories-dictionary_23662.png")));
        dc.insertFromFile();
        setLocation(200,20);
        textac = new TextAutoCompleter(JText1);
        textac.addItems(getEnglishWord());
        
        
        this.bindData();
    }
    

    
    
    
    //lấy list từ tiếng Anh
    private ArrayList getEnglishWord(){
        ArrayList getArrayList = new ArrayList();
           
    for(int i = 0 ; i < Dictionary.listWord.size(); i++){
        getArrayList.add(Dictionary.listWord.get(i).EnglishWord);
    }
        Collections.sort(getArrayList);
        return getArrayList;
    }
    
    
   
   //nạp dữ liệu vào list hiển thị mặc định
   private void bindData(){
       
       getEnglishWord().stream().forEach(x ->{
            defautListModel.addElement(x);
       });
       jList1.setModel(defautListModel);
       jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
   
   
   }
   //tìm từ gần thấy nhất
   private void searchFilter(String searchItem){
   
            DefaultListModel filterListModel = new DefaultListModel();
       
            ArrayList stars = getEnglishWord();
       
            for(int i = 0 ; i < stars.size(); i++){
            
                String starName = stars.get(i).toString().toLowerCase();
                if(starName.contains(searchItem.toLowerCase())){
                
                    filterListModel.addElement(stars.get(i));
                
                }
        
            
            }
           
           defautListModel = filterListModel;
           jList1.setModel(defautListModel);
              
       
   
   
   }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        JText1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jScrollPane3.setViewportView(jTextPane2);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("English Translator");
        jScrollPane4.setViewportView(jTextArea1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 51, 153));
        jTextField2.setText("   ENGTRALATORL.COM");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENGTRASLATOR");

        jList1.setForeground(new java.awt.Color(102, 102, 102));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        JText1.setForeground(new java.awt.Color(102, 102, 102));
        JText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JText1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JText1FocusLost(evt);
            }
        });
        JText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JText1MouseClicked(evt);
            }
        });
        JText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText1ActionPerformed(evt);
            }
        });
        JText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JText1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JText1KeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\Tu dien GUI\\DictionaryGUI\\Image\\if_add_126583.png")); // NOI18N
        jButton2.setText("Add ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\Tu dien GUI\\DictionaryGUI\\Image\\if_sound_107193.png")); // NOI18N
        jButton4.setText("Sound");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" Search:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("   ENGTRALATOR");

        ExitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\Tu dien GUI\\DictionaryGUI\\Image\\if_Cancel_1063907.png")); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText(" Explain:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\Tu dien GUI\\DictionaryGUI\\Image\\if_11_Search_106236.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JText1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JText1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText1ActionPerformed
                            // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_JText1ActionPerformed

    public DictionaryForm(JList<String> jList1) {
        this.jList1 = jList1;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new addWord().setVisible(true);
        jList1.setModel(defautListModel);
        ArrayList getArrayList = new ArrayList();
        getArrayList = getEnglishWord();
        textac.addItems(getArrayList);
        
        
     
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String getWord = "" ;
        getWord = JText1.getText();
        if(JText1.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Please Type Word");
        } else {
            
                
        
        try {
                FileInputStream file = new FileInputStream("transcription/" + getWord.trim().toLowerCase()+".mp3");
                Player player = new Player(file);
                player.play();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "There is no pronunciation for this word!");    
            }
        
        
        
        }
        
        
    
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
            // TODO add your handling code here:
        int checkExit = JOptionPane.showConfirmDialog(this, "Are you sure?", "Close app ?", JOptionPane.YES_NO_OPTION);
        if (checkExit == 0) {
            Dictionary.ListExportToFile();
            System.exit(0);
        } else {
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }
            
            
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void JText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JText1MouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_JText1MouseClicked

    private void JText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JText1FocusGained
        // TODO add your handling code here:
           if(JText1.getText().trim().equals("Type word")){
               JText1.setText("");
           }
         
    }//GEN-LAST:event_JText1FocusGained

    private void JText1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JText1FocusLost
        // TODO add your handling code here:
        if(JText1.getText().trim().equals("")){
        
            JText1.setText("Type word");
        
        }
        
        
    }//GEN-LAST:event_JText1FocusLost

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        JText1.setText(jList1.getSelectedValue());
        
        Dictionary.listWord.stream().filter((star) -> (star).EnglishWord.equals(jList1.getSelectedValue())).forEachOrdered((ele)->{
            jTextArea3.setText(ele.kindofWord + "\n" + ele.transcription+ "\n" +"Nghĩa: "+ele.Explain +"\n"+"VD: "+ele.Example + "\n" + "Nghĩa: " + ele.explainExample);
        
        
        });
        
        
        
    }//GEN-LAST:event_jList1MouseClicked

    private void JText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JText1KeyReleased
        // TODO add your handling code here:
        
        searchFilter(JText1.getText());
        
        
        
    }//GEN-LAST:event_JText1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean check = true;
        if(jTextArea3.getText() != "")
        {
            jTextArea3.setText("");
        } 
        
            for(Word e : Dictionary.listWord){
        
                if(e.EnglishWord.equals(JText1.getText().toString().toLowerCase()))
                    {
                    jTextArea3.append(e.kindofWord+"\n"+e.transcription+ "\n" +"Nghĩa: "+e.Explain +"\n"+"VD: "+e.Example + "\n" + "Nghĩa: " + e.explainExample);
                    check = false;
                    }
            }
        if(check){
        
            JOptionPane.showMessageDialog(rootPane, "Not Found in Dictionary");
        
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jButton1MouseClicked

    private void JText1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JText1KeyPressed
        // TODO add your handling code here:
        boolean check = true;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ){
            
             if(jTextArea3.getText() != "")
            {
                jTextArea3.setText("");
            } 
        
            for(Word e : Dictionary.listWord){
        
                    if(e.EnglishWord.equals(JText1.getText().toString().toLowerCase()))
                        {
                         jTextArea3.append(e.kindofWord+"\n"+e.transcription+ "\n" +"Nghia: "+e.Explain +"\n"+"VD: "+e.Example + "\n" + "Nghia: " + e.explainExample);
                         check = false;
                        }
                    
            }
            if(jTextArea3.getText().equals("")){
            
               jTextArea3.append("NOT DATA IN DICTIONARY!");
            }
        }
        
        
    }//GEN-LAST:event_JText1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField JText1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables


}
